# Generated by Django 3.2.1 on 2023-06-14 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='canal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCanal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='suscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDeSuscripcion', models.DateField()),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.usuario')),
            ],
        ),
    ]
